package com.itstep.onlinephoneshop.entity;
// Generated Feb 27, 2023, 7:24:11 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "phone_shop_db")
public class Brand implements java.io.Serializable {

	private Integer brandId;
	private String name;
	private Set<Phone> phones = new HashSet<Phone>(0);

	public Brand() {
	}

	public Brand(String name) {
		this.name = name;
	}

	public Brand(String name, Set<Phone> phones) {
		this.name = name;
		this.phones = phones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "brand_id", unique = true, nullable = false)
	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<Phone> getPhones() {
		return this.phones;
	}

	public void setPhones(Set<Phone> phones) {
		this.phones = phones;
	}

}
